name: ["COMPARISON_DMPC_MLR_DMPC"]

num_drones: [10, 16]
message_loss_probability: [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]
ignore_message_loss: [False, True]
num_computing_agents: [1, 2, 3, 4, 5, 7, 9, 11]

trigger: ["HT"]
use_kkt_trigger: [False]