name: "demo_visitors"

run_on_cluster: False

# this is used to optimize hyperparameters by hand.
# testbed setup
computing_agent_ids: [20, 21]           # ids of compute units. Length of array defines number of CUs
testbeds:                               # this is only relevant for testbed runs with two testbeds. The simulations always uses Vicon
  "Vicon": [[-1.7, -1.7, 0.3], [1.7, 1.7, 3.0], [0, 0, 0]]

num_drones: 16

# simulation setup
simulated: True     # set false for real testbed (when it runs on a testbed, it saves a bit more data for debugging)
duration_sec: 100   # duration of simulation
abort_simulation: False  # exit simulation earlier, if drones crash or all targets reached.
num_simulations: 1  # number of simulations to conduct
save_video: True
resolution_video: 512   # width of the video in pixels. Height is calculated as resolution_video*9/16
simulate_quantization: False  # simulate quantization during communication
sim_steps_per_control: 4

show_print: False

log_optimizer: False
log_optimizer_path: "../../dampc_dataset"

hpc_saving_path: "../../simulation_results/dmpc"   # only needed when running multiple simulations at once.

message_loss_probability: 0.0

sweep_parameters: False

# Logging options
log: True
log_state: True

#options for target points
use_own_targets: True         # if the cus should use their own targets. This is needed, if we want to use the setpoint_creator for e.g. demos.
# name_sweep

# Controller options
run_dampc: False
dampc_path: "/home/alex/hpc_data/DAMPC_Test/trainer"
dampc_num_layers: 5
dampc_num_neurons: 500
control_steps_per_round: 12
use_communication_freq_hz: True  #weather to calculate communication_freq_hz based on formulas for mixer rounds or to use param communication_freq_hz#
communication_freq_hz: 10

prediction_horizon: 15           # prediction horizon in time is prediction_horizon / communication_freq_hz
r_min: 0.25                       # distance to used during optimization
downwash_scaling_factor: 6
r_min_crit: 0.1                 # simulation considers drones crashed whe drones closer than this
downwash_scaling_factor_crit: 4
use_soft_constraints: False      # always keep this false, true not tested
soft_constraint_max: 0.2
weight_soft_constraint: 0.01
skewed_plane_BVC: False          # always keep this false, true not tested
use_qpsolvers: True
remove_redundant_constraints: False  # always keep false, true deprecated
min_distance_cooperative: 0.1   # for cooperative objective function (deprecated)
cooperative_normal_vector_noise: 0.0  # for cooperative objective function (deprecated)
weight_cooperative: 0.0
weight_state: 1.0
weight_speed: 0.0001
weight_acc: 0.005
weight_jerk: 0.001
weight_band: 0.5                # weight for band that introduces a rotation to the anti collisions constraints
width_band: 0.3                 # width of the band

ignore_message_loss: True      # ignore the occurences of message loss
use_optimized_constraints: True  # remove!!
guarantee_anti_collision: True   # if false uses a deprecated approach

# event trigger options
trigger: "HT"
use_kkt_trigger: False

# high level planner options to resolve deadlocks
use_high_level_planner: True
agent_dodge_distance: 0.5      # the distance an agent move to dodge another agent

